name = "<FUNCTION NAME>"
type = "webpack"

account_id = ""
workers_dev = true
route = ""
zone_id = ""
webpack_config = "webpack.config.js"
compatibility_date = "2021-11-11"

[triggers]
crons = ["* * * * *"]

[vars]
GITHUB_TOKEN = "<GITHUB_TOKEN>"
GITHUB_USER = "<GITHUB_USER>"
GITHUB_REPO = "<GITHUB_REPO>"
AUTO_SIGN = "[A]"
