name = "slack-message"
type = "webpack"

account_id = ""
workers_dev = true
route = ""
zone_id = ""
webpack_config = "webpack.config.js"
compatibility_date = "2021-11-11"
kv_namespaces = [
  { binding = "MEMBERS", id = "d74755004443452fa18a0320cf727921", preview_id="d74755004443452fa18a0320cf727921" }
]


[vars]
SLACK_BOT_TOKEN = "xoxb-798455527522-3263256306068-effdTepFCE99AKBcLTexGVxS"